### ISSUE TITLE
Meaning of program variable

### ISSUE THREAD

**Issue by dxxxxxxxg305** [irfancn/Abaqus-VUMAT-Gurson_GTN#1]
Thank you for contributing this code. I'd like to ask about the specific meaning of 27 variables?

**Comment by irfancn** [comment]
The input parameter 27 (tol = props(27)) corresponds to the tolerance of the Gurson potential (phi) assigned for the iteration. This can be varied considering the accuracy and the processing time.

**Comment by dxxxxxxxg305** [comment]
I mean, all variables

> The input parameter 27 (tol = props(27)) corresponds to the tolerance of the Gurson potential (phi) assigned for the iteration. This can be varied considering the accuracy and the processing time.

I mean, all variables

**Comment by dxxxxxxxg305** [comment]
In ABAQUS, the volume fraction of nucleation cavity fn, nucleation strain en, standard deviation sn. In your code, I found fndev, fnamp, fnmean and fsdev, fsamp, fsmean. I want to understand the meaning of all your variables

**Comment by irfancn** [comment]
I have uploaded the documentation of the numerical implementation. I hope it'll clear things up. Thank you.

**Comment by dxxxxxxxg305** [comment]
I have seen the PDF file you uploaded. Thank you very much for your contribution. I'm sorry to disturb you for the second time. I checked the two literatures you cited and the original document "analysis of the cup cone structure in a round tensile bar, Acta metallurgica". 
I found that the expression of void volume fraction f in the code was something wrong, it should be ‘f = fc + (1.d0/q1 - fc)*(fs - fc)/(ff - fc)’instead of ‘f = fc + 1.d0/(q1 - fc)*(fs - fc)/(ff - fc)’. 
If I disturb you, you can refuse to respond to me. But I still hope to have your reply.
Sincerely！

**Comment by irfancn** [comment]
You are absolutely right. That's an error by me and I'll modify it in the code. Thank you for pointing out.

**Comment by Coding-1-2-3-4-5-6-7-8-9-0** [comment]
Thank you so much for open-sourcing the GTN code. While studying your code, I noticed that the `sigT` variable is undeclared. I'd really like to know the meaning of this variable and would appreciate your help. Thank you.
